### ISSUE TITLE
Vite dev server

### ISSUE THREAD

**Issue by pszczesniak** [ChaDonSom/laravel-vite-template#2]
Hi :)

You did a great laravel vite template! But i have a problem with running Vite server after `npm run dev` i cant open localhost:3000 - returns 404 error. 
When i execute `npm start` i can open 127.0.0.1:8000 but port 3000 is still unavailable. What im doing wrong?

Thanks in advance,
Piotrek

**Comment by pszczesniak** [comment]
On 127.0.0.1:8000 hmr is working fine so... i can live with it 😀

**Comment by ChaDonSom** [comment]
Yes, this is the way Enzo Innocenzi designed his [Laravel Vite](https://laravel-vite.dev/) package, which I used to set this up. That caused me a good bit of confusion too, when I first tried his package 😅

I definitely need to work on some documentation for this project, and also figure out if there is a way to access the `:3000` vite server if needed.

Thanks for your time and input!

**Comment by pszczesniak** [comment]
Thank you for explanation!

Documentation would be a superb thing :)

I have to remember what problems I had during instalation (win10) - will wrote it here or maybe will do a pull request.

One thing for now i've noticed - tailwind is not buildiung css with classes that i want to use... for example i want to use grid on my project and tailwindcss is not buulding it for me... trying to figure it out how to fix it (this is my first approach with tailwind).

**Comment by pszczesniak** [comment]
Again auto-resolved-isse ;) Ive cerated in `/views` folders files with views of pages, they wasnt added into tailwind.config.js in content... Sorry for distrubing :)

**Comment by pszczesniak** [comment]
all is good ;)
